"""Assemble an author brief from its owners - no hand-typed numbers, no
hand-picked exemplars.

The brief is derived, per the one-owner rule: trap numbers come from
trap_ledger (which reads the gate constants), the vocabulary and canon are
included verbatim from their files, and the board section lists the current
board's sentences from the curator's own key - so the "differ from all of
these at the level of formal principle" demand (NoveltyBench's best-in-class
regeneration, canon §10) always names today's board, not a remembered one.

    python tools/make_brief.py <track> <out.md> [assignment-text-file]
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
ROOT = Path(__file__).resolve().parents[1]


def board_section(track: str) -> str:
    key = json.loads((ROOT / "runs" / "board" / "board-key.json")
                     .read_text(encoding="utf-8"))
    book = {}
    for path in sorted((ROOT / "inputs").glob("gen-*.json")):
        for scheme in json.loads(path.read_text(encoding="utf-8"))["schemes"]:
            book[scheme["name"]] = scheme
    lines = ["## 현재 보드 (전량) — 아래 전부와 **형태 원리 수준에서** 달라야 한다",
             "(같은 원리의 변주는 보드에 못 오른다 — 가족당 1석, 큐레이터가 계산함)", ""]
    for row in key:
        if not row["label"].startswith(track):
            continue
        family = row["name"].split("~")[0].split("^")[0]
        scheme = book.get(family) or {}
        line = (scheme.get("secondary_language")
                or scheme.get("formal_principle") or family)
        lines.append(f"- {row['label']} ({row['score']:.2f}): {line}")
    return "\n".join(lines)


def champion_section() -> str:
    """Developments that beat their parent in front of a blind jury.

    The development loop's one real output is a champion, and champion.json
    was read by nothing - so a mutation a jury had already preferred was
    invisible to the next author, who could propose the parent's value again
    with no way of knowing it had been tried and beaten. Read from the
    develop runs' own files, never typed here, and it names the juror count
    because a one-juror round is one opinion, not a consensus.
    """

    lines = []
    for path in sorted(ROOT.glob("runs/develop-*/champion.json")):
        record = json.loads(path.read_text(encoding="utf-8"))
        # A champion.json written before the scorer counted jurors cannot say
        # how many voted, and the brief must not claim a consensus it has no
        # evidence for. Re-score that round and it appears.
        if not record.get("champion") or "jurors" not in record:
            continue
        lines.append(
            f"- **{record['champion']}** — {record.get('champion_change', '-')}"
            f" : 부모 {record['parent']}와의 눈먼 쌍비교에서 심판"
            f" {record.get('jurors', 0)}인 전원이 이 변형을 골랐다")
    if not lines:
        return ""
    return "\n".join(
        ["## 발전 챔피언 (부모를 이긴 변형 — 이미 코퍼스에 있음)",
         "이 파라미터는 이미 판정을 받았다. 부모 쪽 값으로 되돌리는 문장은 같은 비교에서 진다.",
         ""] + lines)


def main(track: str, out_path: str, assignment: str = "") -> int:
    from trap_ledger import ledger  # django setup inside

    parts = [
        "# 저작 브리프 — 소유자들에게서 조립됨 (tools/make_brief.py)",
        "",
        "출력은 {\"schemes\":[...]} JSON 하나뿐이다. 정확히 8문장. 각 scheme 키: name,",
        "primary_language, secondary_language, formal_principle(한국어 한 문장),",
        "dominant_gesture, reference_basis(사실만 또는 \"저작 신작\"), floor_height_m,",
        "ops(각 {\"op\":..., 파라미터, \"why\": 입력→연산자→변형→기능→한계}).",
        "모든 파라미터는 비율. 첫 op는 extrude|loop|aggregate|stack.",
        "",
        "## 사고 절차 (CoT — 문장마다 이 순서로 why를 전개하라)",
        "1) 이 대지·프로그램의 실제 갈등/질문 하나를 명시한다",
        "2) 그 답이 되는 형태 원리를 한 문장으로 선언한다",
        "3) 보드의 어떤 안과도 그 원리가 다른지 확인한다 (아래 보드 절 참조)",
        "4) 원리를 동사 열로 번역한다 — 각 단어의 한계까지",
        "",
    ]
    if assignment:
        parts += ["## 이 저자의 칸 (앵커)", assignment.strip(), ""]
    verdicts = ROOT / "runs" / "board" / "verdict-ledger.md"
    if verdicts.exists():
        # What the juries keep refusing, in their own clauses - generated by
        # verdict_ledger.py from every judged round, never typed here.
        parts += [verdicts.read_text(encoding="utf-8"), ""]
    champions = champion_section()
    if champions:
        parts += [champions, ""]
    parts += [ledger(), "", board_section(track), "",
              "---", "",
              (ROOT / "inputs" / "VOCABULARY.md").read_text(encoding="utf-8"),
              "", "---", "",
              (ROOT / "inputs" / "AUTHORING-CANON.md").read_text(encoding="utf-8")]
    Path(out_path).write_text("\n".join(parts), encoding="utf-8")
    print(f"brief -> {out_path} ({Path(out_path).stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    track = sys.argv[1] if len(sys.argv) > 1 else "O"
    out = sys.argv[2] if len(sys.argv) > 2 else "brief.md"
    text = Path(sys.argv[3]).read_text(encoding="utf-8") if len(sys.argv) > 3 else ""
    sys.exit(main(track, out, text))
